#+OPTIONS: toc:1 |:t ^:nil tags:nil
#+TITLE: Laser Lickport
#+AUTHOR: Jeff Talbot
#+EMAIL: Overlord@jstalbot.com, talbotj@janelia.hhmi.org

* Library Information
- Name :: laser Lickport
- Version :: 0.0.1
- License :: BSD
- URL :: https://github.com/JSTalbotHHMI/LaserLickPort
- Author :: Jeff Talbot
- Email :: talbotj@janelia.hhmi.org


** Description

This repository contains the documentation required to order, fabricate, and operate several variations of the Janelia Laser Lickport

The Laser Lickport was devised to be a noiseless lick detection solution for free-roaming mice and rats undergoing electrophysiology recordings. With this soultion, the electronics of the sensor are moved as far from the test subjects as is needed, and the optical components of the detector do not represent a significant hindrance to the movement of the subjects.

## License 

BSD; Please refer to the [LICENSE](./LICENSE) for the full terms.

## Support

This project is provided as-is, and may be updated over time. If you have questions, please open an issue.