#+OPTIONS: toc:1 |:t ^:nil tags:nil
#+TITLE: Laser Lickport
#+AUTHOR: Jeff Talbot
#+EMAIL: Overlord@jstalbot.com, talbotj@janelia.hhmi.org

* Library Information
- Name :: laser Lickport
- Version :: 0.0.1
- License :: BSD
- URL :: https://github.com/JSTalbotHHMI/LaserLickPort
- Author :: Jeff Talbot
- Email :: Overlord@jstalbot.com, talbotj@janelia.hhmi.org


** Description

This repository contains the documentation required to order, fabricate, and operate several variations of the Janelia Laser Lickport. Please see the methods paper [here](https://en.wikipedia.org/wiki/Near-infrared_spectroscopy) (link not currently functional) for a full explanation of the detection technology.

The Laser Lickport was devised to be a noiseless lick detection solution for free-roaming mice and rats undergoing electrophysiology recordings. All sensing electronics can be located as far from the subjects as is needed, and the optical components of the detector do not represent a significant hindrance to the movement of the subjects.

The available workshops are:

- **[One hour](./content/1-hour/README.md)** — focused on GitHub Copilot
- **[Full-day](./content/full-day/README.md)** — a full day-in-the-life of a developer using GitHub for their DevOps processes
- **[GitHub Actions](./content/github-actions/README.md)** — CI/CD pipelines from running tests to deploying to Azure

## License 

BSD; Please refer to the [LICENSE](./LICENSE) for the full terms.

## Support

This project is provided as-is, and may be updated over time. If you have questions, please open an issue.