name=OptDetect
version=0.1.0
author=HHMI Janelia
maintainer=Jeff Talbot (talbotj@janelia.hhmi.org)
sentence= Optical Lickport I2C Library
paragraph= Optical Lickport I2C Library
url=*
category=Communication
architectures=avr
depends=TinyWireS